spring:
  application:
    name: user-service
server:
  port: 808
eureka:
  client:
    service-url:
      defaultZone: ${eurekaClientServiceUrlDefaultZone}
  instance:
      prefer-ip-address: false
#ribbon:
#  eager-load:
#    enabled: true
#    clients: order-service
#        output:
#          destination: hb-users
#          content-type: application/json
#        input:
#          destination: hb-users