spring:
  application:
    name: user-service
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${eurekaClientServiceUrlDefaultZone}
  instance:
      prefer-ip-address: true
ribbon:
  eager-load:
    enabled: true
    clients: order-service