spring:
  application:
    name: user-service
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost
#          zk-nodes: localhost
#      bindings:
#        springCloudBusInput:
#          destination: springCloudBus
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${eurekaClientServiceUrlDefaultZone}
  instance:
      prefer-ip-address: true
ribbon:
  eager-load:
    enabled: true
    clients: order-service
#        output:
#          destination: hb-users
#          content-type: application/json
#        input:
#          destination: hb-users