/**
 * 
 */
package com.aaxiscommerce.channel;

import org.springframework.cloud.stream.annotation.Input;
import org.springframework.cloud.stream.annotation.Output;
import org.springframework.messaging.MessageChannel;
import org.springframework.messaging.SubscribableChannel;

/**
 * @author ezhang
 *
 */
public interface ThirdPartySystemChannel {
	public static final String THIRD_PARTY_UPDATE = "THIRD_PARTY_UPDATE";
	public static final String INPUT = THIRD_PARTY_UPDATE + "_INPUT";
	public static final String OUTPUT = THIRD_PARTY_UPDATE + "_OUTPUT";

	/**
	 * Get update comes from topic 'THIRD_PARTY_UPDATE' in event/message bus and
	 * update is generated by generated by 3rd-party system.<br/>
	 * 
	 * @return
	 */
	@Input(value = INPUT)
	SubscribableChannel subscribe();

	/**
	 * Publish update to topic 'THIRD_PARTY_UPDATE' in event/message bus and
	 * update is generated by 3rd-party system.<br/>
	 * 
	 * @return
	 */
	@Output(value = OUTPUT)
	MessageChannel publish();
}
