spring:
  application:
    name: inventory-service
  zipkin:
    base-url: ${zipkinBaseUrl}
  sleuth:
    sampler:
      percentage: 1
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${eurekaClientServiceUrlDefaultZone}
  instance:
      prefer-ip-address: true

