spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #replace username and password to yours
          uri: https://github.com/wuyao1994/springcloud-verification-Source.git
          search-paths: config-service/configuration
          username: 'elviswu'
          password: 'wuyao8023'

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${eurekaClientServiceUrlDefaultZone}
  instance:
    prefer-ip-address: false

