spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #replace username and password to yours
          uri: https://elviswu@stash.aaxisgroup.net/scm/ath/springcloud-verification.git
          label: feature/ACCP-8-spring-streaming-data-integration-with-kafka
          search-paths: config-service/configuration
          username: 'elviswu'
          password: ']wuyao8023'

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${eurekaClientServiceUrlDefaultZone}
  instance:
    prefer-ip-address: true

